#!/bin/bash

# This software is licensed under GPL v3 and is provided as-is with no guarantee of suitability for a particular purpose. Use at your own risk. This is a module of the spgu script.

# Colors
	GREEN_BOLD=`echo -en "\e[1;32m"`
	RED=`echo -en "\e[31m"`
	BLUE_BOLD=`echo -en "\e[1;34m"`
	NORMAL=`echo -en "\e[0m"`

# PROMPT
# Distrobox update
echo ""
read -p "${BLUE_BOLD}Would you like to update the distrobox \"tumbleweed-latest\" now Y/n? ${NORMAL}" ANSWER0
case "$ANSWER0" in
	"" | [yY] | yes)
		distrobox enter tumbleweed-latest -- sudo zypper dup
		echo "${GREEN_BOLD}Distrobox update complete!${NORMAL}"
		;;
	[nN] | no)
		echo "Skipping this step..."
		;;
	*)
		echo "${RED}ERROR:${NORMAL} Invalid response - Aborted."
		exit 2
		;;
esac
