#!/bin/bash
echo "Welcome to Soul's Pretty Good Updater v1.0.1 for Debian based systems." | fold -sw $(tput cols)
echo "This software is licensed under GPL v3 and is provided as-is with no guarantee of suitability for a particular purpose. Use at your own risk." | fold -sw $(tput cols)
echo ""

# VARIABLES
# Modules
# Set these to "false" to disable the relevant module
	APTMOD="true"
	FLATMOD="true"
# Colors
	GREEN=`echo -en "\e[0;32m"`
	GREEN_BOLD=`echo -en "\e[1;32m"`
	RED=`echo -en "\e[31m"`
	BLUE=`echo -en "\e[0;34m"`
	BLUE_BOLD=`echo -en "\e[1;34m"`
	NORMAL=`echo -en "\e[0m"`
# Stable
	ISSTABLE="true"

# INDEV
# This section warns the user they are using a development version of the application. Use the ISSTABLE variable above to control this.
if [ "$ISSTABLE" == "true" ]
then
	:
else
	read -p "${RED}WARNING:${NORMAL} This is a development version - code may be unstable! Proceed anyways y/N? " ANSWERx
	case "$ANSWERx" in
		[yY])
			echo "Proceeding..."
			echo "Thank you for testing this software! Please report any bugs you find."
			echo ""
			;;
		*)
			echo "Aborted."
			exit 0
			;;
	esac
fi

# MODULE CHECKS
if [ "$APTMOD" == "true" ]
then
	echo "Base module is ${GREEN}ACTIVE${NORMAL}"
else
	echo "Base module is ${RED}INACTIVE${NORMAL}"
fi
if [ "$FLATMOD" == "true" ]
then
	echo "Flatpak module is ${GREEN}ACTIVE${NORMAL}"
else
	echo "Flatpak module is ${RED}INACTIVE${NORMAL}"
fi
echo "Custom distrobox module is ${RED}INACTIVE${NORMAL}"
echo ""

# PROMPT
# Apt update
if [ "$APTMOD" == "true" ]
then
	read -p "${BLUE_BOLD}Would you like to update apt now Y/n? ${NORMAL}" ANSWER0
	case "$ANSWER0" in
		"" | [yY] | yes)
			sudo apt update && sudo apt upgrade -y
			echo "${BLUE_BOLD}Checking for unneeded apt dependencies...${NORMAL}"
			sudo apt autoremove -y
			echo "${GREEN_BOLD}Apt update complete!${NORMAL}"
			echo ""
			;;
		[nN] | no)
			echo "Skipping this step..."
			;;
		*)
			echo "${RED}ERROR:${NORMAL} Invalid response - Aborted."
			exit 2
			;;
	esac
else
	:
fi

# Flatpak update
if [ "$FLATMOD" == "true" ]
then
	read -p "${BLUE_BOLD}Would you like to update flatpak now Y/n? ${NORMAL}" ANSWER1
	case "$ANSWER1" in
		"" | [yY] | yes)
			flatpak update -y
			echo "${BLUE_BOLD}Checking for unneeded flatpak dependencies...${NORMAL}"
			flatpak uninstall --unused -y
			echo "${GREEN_BOLD}Flatpak update complete!${NORMAL}"
			;;
		[nN] | no)
			echo "Skipping this step..."
			;;
		*)
			echo "${RED}ERROR:${NORMAL} Invalid response - Aborted."
			exit 2
			;;
	esac
else
	:
fi

# Additional modules
# Uncomment below item(s) to activate or add your own
#./distrobox-upd # For portable install
#distrobox-upd # For full install


# Exit message
echo "${BLUE_BOLD}--------------------${NORMAL}"
echo "${GREEN_BOLD}All updates complete!${NORMAL}"
